Ian
cdev-framework/cdev-website pull request #12
Opened 2022-07-12 20:15 UTC by ianick87

Checked the serverless function and bucket examples and made some changes.

2022-07-13 00:50 UTC, Pia007 requested changes
Hi Ian, I have reviewed your PR and I have suggested some minor changes. I think that @DanielSanchez97 @jtfrench23 will have more insight to the code snippets.

2022-07-13 00:50 UTC, Pia007 commented on README.md
> +hugo server
Consider using three backticks, ```, for each of lines 11 thru 14.

2022-07-13 00:50 UTC, Pia007 commented on content/docs/examples/functions.md
> -One of the most important aspects of Serverless Functions is that they can triggered by different `Events`. By passing an `Event` construct into the args of your `Serverless Function`, your deployed
change Api to `API`

2022-07-13 00:50 UTC, Pia007 commented on content/docs/examples/functions.md
> +One of the most important aspects of Serverless Functions is that they can be triggered by different `Events`. By passing an `Event` construct into the args of your `Serverless Function`, your deploy
change Api to `API`

2022-07-13 00:50 UTC, Pia007 commented on content/docs/examples/functions.md
>  You can now get the url of the created `Api` and execute your function by going to the `/hello` route.
change Api to `API`

2022-07-13 13:46 UTC, ianick87 commented
Hey Pia, I made the changes you suggested and I'm going to add Daniel to review the PR. Thank you!

2022-07-13 14:34 UTC, Pia007 requested changes
Hi Ian, sorry for any confusion. My comment contains a better explanation.

2022-07-13 14:34 UTC, Pia007 commented on README.md
> +```wget https://github.com/gohugoio/hugo/releases/download/v0.93.3/hugo_0.93.3_Linux-64bit.deb
Hi Ian, I am sorry for any confusion. I meant for Line 11, 12 & 14, wrap each line in 3 backticks to denote a code block. I have included an image of an example below.   
11
[![image](https://user-images.githubusercontent.com/66088725/178757184-81cfe340-bdef-487b-b87d-df3aadd12525.png)](https://raw.githubusercontent.com/cdev-framework/assemblit/main/CONTRIBUTING.md?token=GHSAT0AAAAAABH4LER5TNJWQLGUO3FLYRFOYWO2VWA)

2022-07-13 15:28 UTC, Pia007 approved these changes
Looks good, Ian!

2022-07-14 00:02 UTC, DanielSanchez97 approved these changes
Looks good to me (LGTM). Only thing is next time make the branch name descriptive of what the changes are.

2022-07-14 04:24 UTC, merged