added scan function in the resource.py and fixed typo
cdev-framework/cdev-website pull request #14
Opened 2022-07-15 16:39 UTC by jtfrench23

I added a scan function so that users can check the entries in the database they created.  This will add confidence to the user that they have been successful in setting up the db.  Let me know if you think it is worth adding some information on NoSQL databases and when to use them in this example, that may be unnecessary information for the example and we can assume that if a person is using this example they already know about NoSQL and DynamoDB otherwise they would probably be looking at the relationalDB example instead.  Just give me your thoughts and I can move forward from there.

2022-07-15 17:05 UTC, Pia007 requested changes
Hi Jordan, it looks good. Left one minor change. I would have to test out the example. Thanks for the explaining your rationale for the scan.

2022-07-15 17:48 UTC, jtfrench23 commented on content/docs/examples/dynamodb.md
> +You can run the function above a few times after making changes to the email address (and other fields if you wish, but the email is mandatory as it is the primary key), to add more entries to your d
good catch

2022-07-15 18:49 UTC, Pia007 approved these changes
Looks good, Jordan!

2022-07-16 04:12 UTC, ianick87 approved these changes

2022-07-17 13:26 UTC, DanielSanchez97 approved these changes
LGTM

2022-07-18 13:04 UTC, merged