Landing about page content
cdev-framework/cdev-website pull request #19
Opened 2022-07-18 23:34 UTC by DanielSanchez97

Change the landing page content slightly and added more to the about page

2022-07-19 13:24 UTC, Pia007 commented on content/about/_index.md
> +- Expand the amount of people that can create effectively software by themselves and within organizations
Line 11, two suggestions for your consideration
```suggestion
- Expand the amount of people that can effectively create software by themselves and within organizations
```
```suggestion
- Expand the amount of people that can create, effectively, software by themselves and within organizations
```

2022-07-19 13:37 UTC, Pia007 commented on content/about/_index.md
> +Today, we are focused on improving the experience of creating Serverless applications on AWS, but in the future, we will build a development platform that help all members of an organization take adv
Line 39:  add 'will'
```suggestion
 ......that will help ......
```

2022-07-19 14:18 UTC, ianick87 requested changes
I would use "justified text alignment" for the text.

2022-07-20 13:13 UTC, ianick87 approved these changes

2022-07-20 17:23 UTC, merged