hugo sample and update to static site examples - draft
cdev-framework/cdev-website pull request #22
Opened 2022-07-21 05:15 UTC by Pia007

I added the hugo example to the Static Site Examples. In doing so, I had to:
1.  Change the Static Site card body text - made the topic more broad 
2.  Change the Header to be broad and not just about react. 
3.  Change the markdown semantics
4.  Create a static site image folder with 2 subfolders (react & hugo ) - made the necessary changes to the react examples image paths

There is some repetition in the two examples that I am hoping for suggestion on how to minimize. Thanks!

2022-07-21 13:24 UTC, jtfrench23 approved these changes
LGTM

2022-07-21 13:25 UTC, ianick87 approved these changes

2022-07-21 19:59 UTC, ianick87 approved these changes

2022-07-22 02:09 UTC, DanielSanchez97 commented on content/docs/examples/staticsite.md
> +    "card_body": "Learn how to connect a static frontend to the Static Site Resource",
connect -> host

2022-07-22 02:10 UTC, DanielSanchez97 commented on content/docs/examples/staticsite.md
> +# Connect a Static Frontend to the Static Site Resource
Connect -> Host 

to -> with

2022-07-22 02:10 UTC, DanielSanchez97 commented on content/docs/examples/staticsite.md
> +## Sync React JS to the Static Site Resource
Sync -> Host

2022-07-22 02:15 UTC, DanielSanchez97 commented on content/docs/examples/staticsite.md
>  The initial file structure should resemble the image below. If this is not your starting point for this example, consult the **[Getting Started](/docs/gettingstarted)** section to initialize a `Cdev
Add the `cdev init` command so that the user can copy and paste it to start a new project.

2022-07-22 02:16 UTC, DanielSanchez97 commented on content/docs/examples/staticsite.md
> +/images/staticsite_examples/react_example/root_src_structure.png
broken image link

2022-07-22 02:19 UTC, DanielSanchez97 commented on content/docs/examples/staticsite.md
> +`Hugo` is a static website generator that converts content files, written in markdown, to static HTML and CSS pages. This example with show how Cdev integrates a Hugo site with the `Static Site` Reso
This example shows*

integrates -> host

2022-07-22 02:20 UTC, DanielSanchez97 commented on content/docs/examples/staticsite.md
> +The initial file structure should resemble the image below. If this is not your starting point for this example, consult the **[Getting Started](/docs/gettingstarted)** section to initialize a Cdev p
Again add the command to create a new project `cdev init` for the user to be able to copy

2022-07-22 02:20 UTC, DanielSanchez97 commented on content/docs/examples/staticsite.md
> +    git init
remove tab

2022-07-22 02:21 UTC, DanielSanchez97 commented on content/docs/examples/staticsite.md
> +    git submodule add https://github.com/theNewDynamic/gohugo-theme-ananke.git themes/ananke
remove tab

2022-07-22 02:21 UTC, DanielSanchez97 commented on content/docs/examples/staticsite.md
> +    echo theme = \"ananke\" >> config.toml
remove tab

2022-07-22 02:21 UTC, DanielSanchez97 commented on content/docs/examples/staticsite.md
> +    hugo new posts/my-first-post.md
remove tab

2022-07-22 02:21 UTC, DanielSanchez97 commented on content/docs/examples/staticsite.md
> +    hugo server -D
remove tab

2022-07-22 02:22 UTC, DanielSanchez97 commented on content/docs/examples/staticsite.md
> +/images/staticsite_examples/hugo_example/hugo_src_structure.png
broken link

2022-07-22 02:24 UTC, DanielSanchez97 commented on content/docs/examples/staticsite.md
> +### Connect the Hugo Site to the Static Site Resource
Change to:
Build Hugo Site

2022-07-22 02:24 UTC, DanielSanchez97 requested changes
See comments

2022-07-22 15:53 UTC, ianick87 approved these changes
LGTM

2022-08-22 19:03 UTC, merged