added workshop overview page and cards to different available workshops
cdev-framework/cdev-website pull request #26
Opened 2022-07-28 17:22 UTC by jtfrench23

let me know what you guys think of the layout and make any suggestions of changes.  Right now Workshops has its own tab idk if that is how we want it or not.

2022-07-28 17:27 UTC, ianick87 requested changes
On the left bar, there's an API link that is broken. Not sue if it needs to be something else.

2022-07-28 17:29 UTC, jtfrench23 commented
> 



> On the left bar, there's an API link that is broken. Not sue if it needs to be something else.

yeah that is some issue with the layout I used and the API link not going anywhere.  I need to figure out where these templates are all coming from and make one specific to the workshop pages

2022-07-29 03:13 UTC, DanielSanchez97 commented on content/workshops/fullstack.md
> +This workshop is recommended to developers of all skill levels, that have basic knowledge of fullstack web-development, and are wanting to deploy applications on an AWS server. Cdev is an easy-to-use
on and AWS Server -> on Aws

It can be unclear using 'server' there since we are deploying on a 'serverless' platform.

2022-07-29 03:14 UTC, DanielSanchez97 commented on content/workshops/fullstack.md
> +This workshop is recommended to developers of all skill levels, that have basic knowledge of fullstack web-development, and are wanting to deploy applications on an AWS server. Cdev is an easy-to-use
focussed*

2022-07-29 03:15 UTC, DanielSanchez97 commented on content/workshops/fullstack.md
> +This workshop is recommended to developers of all skill levels, that have basic knowledge of fullstack web-development, and are wanting to deploy applications on an AWS server. Cdev is an easy-to-use
complete -> fullstack

2022-07-29 03:15 UTC, DanielSanchez97 commented on content/workshops/fullstack.md
> +- create a database
create -> Create

2022-07-29 03:16 UTC, DanielSanchez97 commented on content/workshops/fullstack.md
> +>>> Warning: Amazon’s AWS service may charge you for using its service. Any cost related to the use of an AWS service is your responsibility.
maybe use a tooltip? or create a snippet with different css because it currently blends into the page

2022-07-29 03:17 UTC, DanielSanchez97 commented on content/workshops/fullstack.md
> +    "type": "tutorial",
tutorial -> workshop

2022-07-29 03:17 UTC, DanielSanchez97 commented on content/workshops/fullstack.md
> +- basic knowledge of React
Lets add links to cover these technologies.

2022-07-29 03:19 UTC, DanielSanchez97 commented on content/workshops/_index.md
> +We have set up several different workshops to help get you started using Cdev and achieve your programming goals. Check out the available options below, and also feel free to contact us to set up a p
Lets change the end of this to be a stronger Call To Action (CTA) with information about signing up for a workshop; similair to the CTA at the end of the other pages.

2022-07-29 03:20 UTC, DanielSanchez97 commented on content/workshops/frontend.md
> +This workshop is for anyone who has some basic web-development knoledge and an interest in serverless development.
remove 'some'

2022-07-29 03:20 UTC, DanielSanchez97 commented on content/workshops/frontend.md
> +This workshop is for anyone who has some basic web-development knoledge and an interest in serverless development.
knoledge*

2022-07-29 03:21 UTC, DanielSanchez97 commented on content/workshops/frontend.md
> +This workshop is for anyone who has some basic web-development knoledge and an interest in serverless development.
serverless -> Serverless

2022-07-29 03:21 UTC, DanielSanchez97 commented on content/workshops/frontend.md
> +In this workshop we will teach you the basics of using the Cdev SDK and how to create and host a static site.
workshop -> workshop,

2022-07-29 03:22 UTC, DanielSanchez97 commented on content/workshops/frontend.md
> +In this workshop we will teach you the basics of using the Cdev SDK and how to create and host a static site.
remove 'and how to create' because this one will assume they have a site to already host (i.e their resume website or something equivalent)

2022-07-29 03:23 UTC, DanielSanchez97 commented on content/workshops/frontend.md
> +- Python
We can even remove Python because they don't actually need to write any Python

2022-07-29 03:24 UTC, DanielSanchez97 commented on content/workshops/noFrontend.md
> +This workshop is for anyone who is familiar with the Python programming language (at least at a basic level), who is interested in serverless web-development.
remove '(at least at a basic level)'

2022-07-29 03:24 UTC, DanielSanchez97 commented on content/workshops/noFrontend.md
> +This workshop is for anyone who is familiar with the Python programming language (at least at a basic level), who is interested in serverless web-development.
switch the command to an 'and'

2022-07-29 03:25 UTC, DanielSanchez97 requested changes
See comments

2022-07-29 03:28 UTC, DanielSanchez97 commented
In the content files. you need to change the json at the top to be 
````
{
    "type": "workshops",
    ...
```
because right now it is still using the tutorial layout. Once that is changed, it will use your `workshops` layouts and you can remove things like the side bar and arrows at the bottom. 

I think the paragraphs on the `list` page can have more information about the goals/benefits of the workshops and end with a stronger call to action.

2022-07-29 03:31 UTC, DanielSanchez97 commented
I just checked out the other open PR and see that one has the workshop layout properly linked, so disregard any comments that are out of date!

2022-07-29 17:53 UTC, closed without merging