Office hours
cdev-framework/cdev-website pull request #27
Opened 2022-07-28 19:15 UTC by jtfrench23

added office hour page with a link to it from contact us.  Also removed the side bar from the workshops so that the API link isn't there.  Once we know the times we are doing for office hours we can update this and attach links to our calendlys for 1-on-1s

2022-07-28 20:32 UTC, ianick87 reviewed
Just need to make sure the Zoom link works and calendly links the same, other than that LGTM.

2022-07-29 03:38 UTC, DanielSanchez97 commented on layouts/office_hours/single.html
> +    <h1>{{.Title}}</h1>
Center the title by adding `style="text-align: center;"` to the `h1` tag

2022-07-29 03:40 UTC, DanielSanchez97 commented on content/contact/officehours.md
> +Fullstack Developer
Maybe add a code snippet for a card that can take a picture because I like the idea of having our headshots on their to make it more personable

2022-07-29 03:40 UTC, DanielSanchez97 requested changes
see comments

2022-07-29 14:54 UTC, jtfrench23 commented
I made all the changes that were suggested, we still may want more on certain aspects of the workshops.

2022-07-29 17:59 UTC, DanielSanchez97 commented on layouts/office_hours/single.html
> +                <div class="text-center border border-dark  p-2">
Switch these to using the cards from the theme. You can copy and past the html from `layouts/shortcodes/card.html` as a starting place.

2022-07-29 18:00 UTC, DanielSanchez97 requested changes
Looking good! For now the only thing would be the card comment that I left. We can go over it all in more detail Monday morning.

2022-07-29 18:05 UTC, ianick87 reviewed
im not sure what the plan is for the mugshots and the zoom link but other than that looks good to me.

2022-08-01 15:11 UTC, ianick87 approved these changes
LGTM. I'm just not sure about the office hours link still...

2022-08-01 19:53 UTC, ianick87 approved these changes

2022-08-02 12:39 UTC, DanielSanchez97 approved these changes
Looks great!

2022-08-02 12:57 UTC, merged