fixes to grammar and added a couple of clarifying notes
cdev-framework/cdev-website pull request #9
Opened 2022-07-11 19:45 UTC by jtfrench23

2022-07-11 19:49 UTC, ianick87 approved these changes

2022-07-11 20:02 UTC, Pia007 commented on content/docs/examples/relationaldb.md
> +{{<tool_tip key="tip" summary="Database Info">}}
try changing tool-tip key to "info".

2022-07-11 20:12 UTC, Pia007 requested changes
Hi Jordan, I left one comment for a change.

2022-07-12 15:36 UTC, DanielSanchez97 requested changes
One small note, but besides that LGTM

2022-07-12 17:32 UTC, ianick87 approved these changes

2022-07-12 17:57 UTC, Pia007 commented on content/docs/examples/relationaldb.md
> -{{<tool_tip key="tip" summary="Database Info">}}
Hi Jordan, sorry if I was not clear. --- line 24....change `key="tip"`, to `key='info`.

2022-07-12 17:59 UTC, Pia007 approved these changes
Hi Jordan, ignore my last comment.

2022-07-13 23:44 UTC, DanielSanchez97 commented on source_code/relationaldb_examples/basic_db.py
> -  "demo_db",
It should not use variables directly, but instead use keyword arguments. https://www.w3schools.com/python/gloss_python_function_keyword_arguments.asp

```
myDB = RelationalDB(
  cdev_name="demo_db",
  username="username",
  password="password",
  database_name="default_table"
)
```

2022-07-13 23:45 UTC, DanielSanchez97 requested changes
See comment about switching example files to using keyword arguments. Once that is changed, this LGTM

2022-07-14 13:34 UTC, merged